spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mapper5?useUnicode=true&characterencoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

mybatis:
  type-aliases-package: com.zc.model
  configuration:
    map-underscore-to-camel-case: true

logging:
  root: debug